
services:

  app_service:
    build:
      context: './docker/php'
    container_name: app
    volumes:
      - './src:/var/www/html'
    depends_on:
      - postgres_service
    networks:
      - app_network
    ports:
      - 80:8000

  postgres_service:
    container_name: postgres
    image: postgres 
    env_file:
      - .env
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    networks:
      - app_network
    

networks:
  app_network:

